[tool.briefcase]
project_name = "dummyform"
bundle = "com.shahmir.dummyform"
version = "0.0.1"
author = "shahmirqureshi"
author_email = "naeemabbasi806@gmail.com"
url = "https://dummyform.com"
license.file = "LICENSE"

[tool.briefcase.app.dummyform]
formal_name = "Dummy Form"
description = "A dummy form app for testing BeeWare with CSV and XLSX."
sources = ["src/dummyform"]   # <-- folder where app.py lives
requires = ["toga-android~=0.5.0", "openpyxl"]  # <--- declare openpyxl for Android

[tool.briefcase.app.dummyform.android]
base_theme = "Theme.MaterialComponents.Light.DarkActionBar"
build_gradle_dependencies = [
    "com.google.android.material:material:1.12.0",
]
